// models/Syllabus.js
const mongoose = require("mongoose");
const { v4: uuidv4 } = require("uuid");

// Subtopic schema (no autogenerated _id for subdocuments)
const SubtopicSchema = new mongoose.Schema(
  {
    topicName: { type: String, required: true },
    result: { type: String, default: "" },
    subtopics: [],
  },
  { _id: false }
);

// Make it recursive
SubtopicSchema.add({ subtopics: [SubtopicSchema] });

// Main Syllabus schema (explicit collection name = syllabuses as you have in Compass)
const SyllabusSchema = new mongoose.Schema(
  {
    customId: { type: String, default: uuidv4, unique: true, index: true },
    topic: { type: String, required: true },
    subtopics: [SubtopicSchema],
  },
  { collection: "syllabuses" }
);

module.exports = mongoose.model("Syllabus", SyllabusSchema);
